Repository noncelab/coconut_wallet, pull requests merged in 2025-03, with the labels that each got.

#128 [14-1054] Fix/send optimal utxo
  lib/providers/node_provider/transaction/transaction_fetcher.dart
  lib/providers/node_provider/utxo_manager.dart
  lib/providers/view_model/send/send_utxo_selection_view_model.dart
  lib/screens/send/send_utxo_selection_screen.dart
  lib/services/electrum_service.dart
  lib/utils/transaction_util.dart
  lib/widgets/card/selectable_utxo_item_card.dart
Labels: 💫 feat

#129 [14-1021] Fix/wallet list animation
  CONTRIBUTING.md
  lib/enums/currency_enums.dart
  lib/model/utxo/utxo_state.dart
  lib/model/wallet/transaction_record.dart
  lib/providers/upbit_connect_model.dart
  lib/providers/view_model/home/wallet_list_view_model.dart
  lib/providers/view_model/wallet_detail/utxo_list_view_model.dart
  lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart
  lib/providers/wallet_provider.dart
  lib/repository/realm/wallet_repository.dart
  lib/screens/common/text_field_bottom_sheet.dart
  lib/screens/home/wallet_list_screen.dart
  lib/screens/send/send_fee_selection_screen.dart
  lib/screens/wallet_detail/utxo_detail_screen.dart
  lib/screens/wallet_detail/utxo_list_screen.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
  lib/styles.dart
  lib/utils/amimation_util.dart
  lib/widgets/body/utxo_list_body.dart
  lib/widgets/body/wallet_detail_body.dart
  lib/widgets/card/transaction_item_card.dart
  lib/widgets/card/utxo_item_card.dart
  lib/widgets/card/wallet_item_card.dart
  lib/widgets/card/wallet_list_add_guide_card.dart
  lib/widgets/card/wallet_list_terms_shortcut_card.dart
  lib/widgets/dropdown/utxo_filter_dropdown.dart
  lib/widgets/header/utxo_list_header.dart
  lib/widgets/header/utxo_list_sticky_header.dart
  lib/widgets/header/wallet_detail_header.dart
  lib/widgets/textfield/custom_limit_text_field.dart
  pubspec.yaml
Labels: 💫 feat, 🎨 UI

#136 [14-1069] Fix/send amount
  lib/providers/view_model/send/send_amount_view_model.dart
  lib/providers/view_model/send/send_fee_selection_view_model.dart
  lib/providers/view_model/send/send_utxo_selection_view_model.dart
  lib/screens/send/send_amount_screen.dart
Labels: 🐛 bug

#137 [14-1073] feebumping 관련 UI 수정
  lib/screens/wallet_detail/transaction_detail_screen.dart
  lib/widgets/header/wallet_detail_header.dart
Labels: 🎨 UI

#147 [14-1058] RBF 내역 중복/순서 표기 오류 수정
  lib/repository/realm/converter/transaction.dart
  lib/repository/realm/model/coconut_wallet_model.dart
  lib/repository/realm/model/coconut_wallet_model.realm.dart
  lib/repository/realm/transaction_repository.dart
  test/providers/node_provider/transaction_manager_test.dart
  test/providers/node_provider/transaction_manager_test.mocks.dart
Labels: 🐛 bug

#139 [14-1062] wallet-list, transaction-detail, utxo-list잔액 애니메이션 적용
  lib/model/wallet/balance.dart
  lib/providers/view_model/home/wallet_list_view_model.dart
  lib/providers/view_model/wallet_detail/utxo_list_view_model.dart
  lib/screens/home/wallet_list_screen.dart
  lib/screens/wallet_detail/utxo_list_screen.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
  lib/widgets/animated_balance.dart
  lib/widgets/card/wallet_item_card.dart
  lib/widgets/header/utxo_list_header.dart
  lib/widgets/header/utxo_list_sticky_header.dart
  lib/widgets/header/wallet_detail_header.dart
  lib/widgets/header/wallet_detail_sticky_header.dart
Labels: 💫 feat

#149 [14-1092] RBF 받는 지갑 관점에서 UTXO 삭제 안되는 오류 수정
  lib/providers/node_provider/transaction/models/rbf_info.dart
  lib/providers/node_provider/transaction/rbf_handler.dart
  lib/providers/node_provider/transaction/transaction_fetcher.dart
  lib/providers/node_provider/utxo_manager.dart
  lib/services/electrum_service.dart
Labels: 🐛 bug

#145 [14-1038] 시세 렌더링 위젯 생성
  lib/providers/view_model/send/send_confirm_view_model.dart
  lib/screens/send/broadcasting_screen.dart
  lib/screens/send/fee_selection_screen.dart
  lib/screens/send/send_confirm_screen.dart
  lib/screens/send/send_fee_selection_screen.dart
  lib/screens/send/send_utxo_selection_screen.dart
  lib/screens/wallet_detail/transaction_detail_screen.dart
  lib/screens/wallet_detail/utxo_detail_screen.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
  lib/widgets/card/send_fee_selection_item_card.dart
  lib/widgets/card/send_utxo_sticky_header.dart
  lib/widgets/contents/fiat_price.dart
  lib/widgets/header/utxo_list_header.dart
Labels: ♻️ refactor

#143 [14-1083] batch-tx 부분 ui 수정
  lib/providers/view_model/send/send_amount_view_model.dart
  lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart
  lib/screens/send/send_address_screen.dart
  lib/screens/send/send_amount_screen.dart
  lib/screens/wallet_detail/transaction_fee_bumping_screen.dart
  lib/widgets/body/send_address/send_address_amount_body_for_batch.dart
  lib/widgets/button/single_bottom_button.dart
Labels: 🎨 UI

#153 [14-1098] 다른 지갑의 CPFP가 내 지갑의 CPFP로 인식되는 오류
  lib/providers/node_provider/isolate/isolate_manager.dart
  lib/providers/node_provider/transaction/cpfp_handler.dart
  lib/providers/node_provider/transaction/transaction_fetcher.dart
  lib/providers/node_provider/utxo_manager.dart
  lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart
  lib/repository/realm/utxo_repository.dart
  lib/screens/wallet_detail/utxo_list_screen.dart
  test/mock/transaction_mock.dart
  test/providers/node_provider/transaction_manager_test.dart
Labels: 🐛 bug

#152 [14-1097] Batch 트랜잭션 화면 AutoFocus 기능
  lib/widgets/body/send_address/send_address_amount_body_for_batch.dart
  lib/widgets/card/address_and_amount_card.dart
Labels: 💫 feat, 🎨 UI
