Repository noncelab/coconut_wallet, pull requests merged in 2025-07, with the labels that each got.

#364 [358] Unsigned Transaction의 QR 여백 사이즈 조정
  lib/screens/send/unsigned_transaction_qr_screen.dart
  lib/widgets/animated_qr/animated_qr_view.dart
Labels: 💫 feat, 🎨 UI

#376 [374] 영문 UI 수정 사항
  assets/i18n/en.i18n.yaml
  assets/i18n/kr.i18n.yaml
  lib/screens/home/wallet_list_user_experience_survey_bottom_sheet.dart
  lib/screens/review/negative_feedback_screen.dart
  lib/screens/review/positive_feedback_screen.dart
  lib/screens/wallet_detail/transaction_detail_screen.dart
Labels: 🐛 bug

#391 [379] 일렉트럼 서버 변경에 필요한 함수 제공
  lib/app.dart
  lib/constants/external_links.dart
  lib/constants/shared_pref_keys.dart
  lib/enums/electrum_enums.dart
  lib/main.dart
  lib/model/node/electrum_server.dart
  lib/providers/node_provider/node_provider.dart
  lib/providers/preference_provider.dart
  lib/widgets/appbar/frosted_appbar.dart
Labels: 💫 feat

#392 [386] 전체주소보기 툴팁 UI 변경/개선
  assets/i18n/en.i18n.yaml
  assets/i18n/kr.i18n.yaml
  lib/constants/shared_pref_keys.dart
  lib/providers/preference_provider.dart
  lib/screens/home/wallet_add_input_screen.dart
  lib/screens/wallet_detail/address_list_screen.dart
  lib/screens/wallet_detail/wallet_detail_receive_address_bottom_sheet.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
Labels: ♻️ refactor

#380 [375] 최소수수료율 0.1 지원
  assets/i18n/en.i18n.yaml
  assets/i18n/kr.i18n.yaml
  lib/app.dart
  lib/main.dart
  lib/providers/node_provider/isolate/isolate_initializer.dart
  lib/providers/node_provider/isolate/isolate_manager.dart
  lib/providers/node_provider/network_service.dart
  lib/providers/node_provider/node_provider.dart
  lib/providers/view_model/onboarding/start_view_model.dart
  lib/providers/view_model/send/broadcasting_view_model.dart
  lib/providers/view_model/send/send_utxo_selection_view_model.dart
  lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart
  lib/screens/onboarding/start_screen.dart
  lib/screens/send/broadcasting_screen.dart
  lib/screens/send/fee_selection_screen.dart
  lib/screens/send/send_fee_selection_screen.dart
  lib/screens/send/send_utxo_selection_screen.dart
  lib/screens/wallet_detail/transaction_detail_screen.dart
  lib/screens/wallet_detail/utxo_detail_screen.dart
  lib/screens/wallet_detail/wallet_detail_faucet_request_bottom_sheet.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
  lib/services/app_version_service.dart
  lib/services/base_api_service.dart
  lib/services/coconut_api_service.dart
  lib/services/dio_client.dart
  lib/services/faucet_service.dart
  lib/services/mempool_api_service.dart
  lib/services/model/response/recommended_fee.dart
  lib/utils/alert_util.dart
Labels: 💫 feat
