Repository noncelab/coconut_wallet, pull requests merged in 2025-05, with the labels that each got.

#202 [201] 앱 사용중 네트워크 미연결 알림 툴팁 + CoconutAppBar 마이그레이션
  lib/providers/view_model/send/broadcasting_view_model.dart
  lib/providers/view_model/send/send_amount_view_model.dart
  lib/providers/view_model/send/send_utxo_selection_view_model.dart
  lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart
  lib/screens/home/wallet_add_scanner_screen.dart
  lib/screens/home/wallet_list_glossary_bottom_sheet.dart
  lib/screens/home/wallet_list_security_self_check_bottom_sheet.dart
  lib/screens/review/negative_feedback_screen.dart
  lib/screens/review/positive_feedback_screen.dart
  lib/screens/send/broadcasting_screen.dart
  lib/screens/send/fee_selection_screen.dart
  lib/screens/send/send_amount_screen.dart
  lib/screens/send/send_confirm_screen.dart
  lib/screens/send/send_fee_selection_screen.dart
  lib/screens/send/send_utxo_selection_screen.dart
  lib/screens/send/signed_psbt_scanner_screen.dart
  lib/screens/send/unsigned_transaction_qr_screen.dart
  lib/screens/settings/app_info_license_bottom_sheet.dart
  lib/screens/settings/bip39_list_screen.dart
  lib/screens/settings/settings_screen.dart
  lib/screens/wallet_detail/transaction_fee_bumping_screen.dart
  lib/screens/wallet_detail/wallet_detail_receive_address_bottom_sheet.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
  lib/utils/icons_util.dart
  lib/widgets/appbar/custom_appbar.dart
  lib/widgets/overlays/custom_toast.dart
  lib/widgets/overlays/network_error_tooltip.dart
Labels: ♻️ refactor, 🎨 UI

#217 [UI] 태그 색상(gray), '잔돈'툴팁, 숏컷 케밥 아이콘
  assets/i18n/kr.i18n.yaml
  lib/screens/common/tag_bottom_sheet.dart
  lib/screens/wallet_detail/utxo_detail_screen.dart
  lib/utils/colors_util.dart
  lib/widgets/card/selectable_utxo_item_card.dart
  lib/widgets/card/utxo_item_card.dart
  lib/widgets/card/wallet_list_glossary_shortcut_card.dart
Labels: 🎨 UI

#223 [FIX] 지갑 정보 화면 - 이름 변경
  assets/i18n/kr.i18n.yaml
  lib/providers/view_model/wallet_detail/wallet_info_edit_view_model.dart
  lib/screens/wallet_detail/wallet_info_edit_bottom_sheet.dart
  lib/screens/wallet_detail/wallet_info_screen.dart
  lib/widgets/card/wallet_info_item_card.dart
Labels: 🎨 UI

#221 [177] 타사 지갑 비트코인 보내기
  assets/i18n/kr.i18n.yaml
  integration_test/integration_test_utils.dart
  lib/providers/send_info_provider.dart
  lib/providers/view_model/home/wallet_add_input_view_model.dart
  lib/providers/view_model/home/wallet_add_scanner_view_model.dart
  lib/providers/view_model/send/broadcasting_view_model.dart
  lib/providers/view_model/send/send_fee_selection_view_model.dart
  lib/providers/view_model/send/send_utxo_selection_view_model.dart
  lib/providers/view_model/send/signed_psbt_scanner_view_model.dart
  lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart
  lib/providers/view_model/wallet_detail/wallet_info_view_model.dart
  lib/screens/common/qrcode_bottom_sheet.dart
  lib/screens/home/wallet_add_scanner_screen.dart
  lib/screens/home/wallet_list_screen.dart
  lib/screens/send/send_address_screen.dart
  lib/screens/send/send_confirm_screen.dart
  lib/screens/send/signed_psbt_scanner_screen.dart
  lib/screens/send/unsigned_transaction_qr_screen.dart
  lib/screens/settings/app_info_screen.dart
  lib/screens/wallet_detail/wallet_detail_receive_address_bottom_sheet.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
  lib/screens/wallet_detail/wallet_info_screen.dart
  lib/services/wallet_add_service.dart
  lib/utils/third_party_util.dart
  lib/widgets/animated_qr/animated_qr_data_handler.dart
  lib/widgets/animated_qr/animated_qr_scanner.dart
  lib/widgets/animated_qr/animated_qr_view.dart
  lib/widgets/animated_qr/bc_ur_qr_data_handler.dart
  lib/widgets/animated_qr/coconut_qr_scanner.dart
  lib/widgets/animated_qr/scan_data_handler/bc_ur_qr_scan_data_handler.dart
  lib/widgets/animated_qr/scan_data_handler/coconut_wallet_add_qr_scan_data_handler.dart
  lib/widgets/animated_qr/scan_data_handler/descriptor_qr_scan_data_handler.dart
  lib/widgets/animated_qr/scan_data_handler/i_qr_scan_data_handler.dart
  lib/widgets/animated_qr/view_data_handler/bc_ur_qr_view_handler.dart
  lib/widgets/animated_qr/view_data_handler/coconut_qr_view_handler.dart
  lib/widgets/animated_qr/view_data_handler/i_qr_view_data_handler.dart
  lib/widgets/body/send_address/send_address_body.dart
  lib/widgets/card/address_and_amount_card.dart
  lib/widgets/qrcode_info.dart
  pubspec.yaml
  test/packages/bc_ur_test.dart
  test/utils/descriptor_util_test.dart
  test/widgets/animated_qr_data_handler_test.dart
Labels: 💫 feat

#244 fix(replaced-tx): 대체된 트랜잭션 판단 기준에 FeeRate 비교 로직 추가
  lib/providers/node_provider/transaction/transaction_sync_service.dart
  test/providers/node_provider/transaction_sync_service_test.dart
Labels: 🐛 bug

#247 fix(walletImportSource): rbf/cpfp 과정에서 값 설정 누락
  lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart
Labels: 🐛 bug

#250 [#245] RBF 직후 일렉트럼 UTXO 조회 시 데이터 정합성 오류 대응
  lib/constants/realm_constants.dart
  lib/providers/node_provider/isolate/isolate_controller.dart
  lib/providers/node_provider/isolate/isolate_manager.dart
  lib/providers/node_provider/node_provider.dart
  lib/providers/node_provider/state/isolate_state_manager.dart
  lib/providers/node_provider/subscription/script_callback_service.dart
  lib/providers/node_provider/subscription/script_sync_service.dart
  lib/providers/node_provider/transaction/rbf_service.dart
  lib/providers/node_provider/transaction/transaction_sync_service.dart
  lib/providers/node_provider/utxo_sync_service.dart
  lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart
  lib/repository/realm/migration/migration.dart
  lib/repository/realm/model/coconut_wallet_model.dart
  lib/repository/realm/transaction_repository.dart
  lib/repository/realm/utxo_repository.dart
  test/providers/node_provider/subscription/script_callback_service_test.dart
  test/providers/node_provider/transaction/cpfp_service_test.dart
  test/providers/node_provider/transaction/rbf_service_test.dart
  test/repository/realm/transaction_repository_test.dart
  test/repository/realm/utxo_repository_test.dart
Labels: 🐛 bug

#255 [#248] 앱 이탈 - 복귀 - 트랜잭션 발생 시 지갑 구독해제/구독 함수 수차례 호출
  lib/providers/node_provider/node_provider.dart
  lib/providers/wallet_provider.dart
Labels: 🐛 bug
