Repository noncelab/coconut_wallet, pull requests merged in 2025-06, with the labels that each got.

#261 [#260] Realm 뷰어 화면 개발
  lib/screens/settings/realm_debug_screen.dart
  lib/screens/settings/settings_screen.dart
Labels: 💫 feat

#286 [#285] 키스톤 지갑 때문에 중복 지갑 찾기 실패
  lib/providers/wallet_provider.dart
Labels: 🐛 bug

#304 [302] OP_RETURN 트랜잭션 표기 수정
  lib/providers/node_provider/transaction/transaction_record_service.dart
Labels: 🐛 bug

#314 [313] 주소 스캔 화면 - 포그라운드로 복귀 시 붙여넣기 활성화 되도록 개선
  lib/providers/view_model/send/send_address_view_model.dart
  lib/screens/send/send_address_screen.dart
Labels: 🐛 bug

#310 [284, 298] 사용 전 주소 옵션, 주소 스크롤 최적화
  assets/i18n/kr.i18n.yaml
  assets/svg/arrow-back.svg
  lib/app.dart
  lib/constants/address.dart
  lib/constants/shared_pref_keys.dart
  lib/providers/preference_provider.dart
  lib/providers/view_model/wallet_detail/address_list_view_model.dart
  lib/providers/view_model/wallet_detail/address_search_view_model.dart
  lib/providers/wallet_provider.dart
  lib/repository/realm/address_repository.dart
  lib/repository/realm/converter/address.dart
  lib/screens/wallet_detail/address_list_screen.dart
  lib/screens/wallet_detail/address_search_screen.dart
  pubspec.yaml
  test/providers/node_provider/subscription/script_sync_service_test.dart
  test/repository/realm/address_repository_test.dart
Labels: 💫 feat, ♻️ refactor

#338 [228] QR 정보량 조정 기능
  assets/i18n/kr.i18n.yaml
  lib/screens/send/signed_psbt_scanner_screen.dart
  lib/screens/send/unsigned_transaction_qr_screen.dart
  lib/utils/vibration_util.dart
  lib/widgets/animated_qr/animated_qr_view.dart
  lib/widgets/animated_qr/coconut_qr_scanner.dart
  lib/widgets/animated_qr/scan_data_handler/bc_ur_qr_scan_data_handler.dart
  lib/widgets/animated_qr/scan_data_handler/coconut_wallet_add_qr_scan_data_handler.dart
  lib/widgets/animated_qr/scan_data_handler/descriptor_qr_scan_data_handler.dart
  lib/widgets/animated_qr/scan_data_handler/i_qr_scan_data_handler.dart
  lib/widgets/animated_qr/view_data_handler/bc_ur_qr_view_handler.dart
Labels: 💫 feat
