Repository noncelab/coconut_wallet, pull requests merged in 2025-08, with the labels that each got.

#400 [384] 콜드카드 호환
  assets/i18n/en.i18n.yaml
  assets/i18n/kr.i18n.yaml
  assets/svg/cold-card.svg
  lib/constants/icon_path.dart
  lib/enums/wallet_enums.dart
  lib/providers/view_model/home/wallet_add_scanner_view_model.dart
  lib/providers/view_model/send/broadcasting_view_model.dart
  lib/screens/home/wallet_add_scanner_screen.dart
  lib/screens/home/wallet_list_screen.dart
  lib/screens/send/broadcasting_screen.dart
  lib/screens/send/signed_psbt_scanner_screen.dart
  lib/screens/send/unsigned_transaction_qr_screen.dart
  lib/services/wallet_add_service.dart
  lib/utils/bbqr/bbqr_decoder.dart
  lib/utils/bbqr/bbqr_encoder.dart
  lib/utils/logger.dart
  lib/utils/third_party_util.dart
  lib/widgets/animated_qr/scan_data_handler/bb_qr_scan_data_handler.dart
  lib/widgets/animated_qr/scan_data_handler/raw_signed_bitcoin_transaction_scan_data_handler.dart
  pubspec.yaml
Labels: 💫 feat

#416 [415] 써드파티로 지갑 추가시 발생하는 버그 수정
  lib/providers/view_model/home/wallet_add_scanner_view_model.dart
  lib/providers/wallet_provider.dart
  lib/widgets/icon/wallet_item_icon.dart
Labels: 🐛 bug

#406 [401] 사용자 지정 노드: tor 및 vpn tunneling 환경 지원
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/onl/coconut/wallet/MainActivity.kt
  assets/i18n/en.i18n.yaml
  assets/i18n/kr.i18n.yaml
  ios/Runner/Info.plist
  lib/constants/isolate_constants.dart
  lib/constants/shared_pref_keys.dart
  lib/model/node/electrum_server.dart
  lib/providers/node_provider/isolate/isolate_manager.dart
  lib/providers/node_provider/network_service.dart
  lib/providers/preference_provider.dart
  lib/providers/view_model/settings/electrum_server_view_model.dart
  lib/repository/shared_preference/shared_prefs_repository.dart
  lib/screens/settings/electrum_server_screen.dart
  lib/services/electrum_service.dart
  lib/services/network/socket/socket_factory.dart
  lib/services/network/socket/socket_manager.dart
  lib/widgets/button/shrink_animation_button.dart
  lib/widgets/custom_dialogs.dart
Labels: 💫 feat

#431 [FIX] 안드로이드 백버튼 클릭 시 키보드 위 요소가 남아있음
  lib/screens/send/refactor/send_screen.dart
Labels: 🐛 bug

#426 [Feat] JPY 시세 지원
  assets/i18n/en.i18n.yaml
  assets/i18n/kr.i18n.yaml
  lib/enums/fiat_enums.dart
  lib/providers/price_provider.dart
  lib/screens/settings/fiat_bottom_sheet.dart
  lib/screens/settings/settings_screen.dart
  lib/services/web_socket_service.dart
Labels: 💫 feat

#429 [427] 잔액 숨김/보이기 로직과 가짜잔액 로직 분리
  lib/providers/preference_provider.dart
  lib/providers/view_model/home/wallet_add_input_view_model.dart
  lib/providers/view_model/home/wallet_add_scanner_view_model.dart
  lib/providers/wallet_provider.dart
  lib/screens/home/wallet_add_input_screen.dart
  lib/screens/home/wallet_add_scanner_screen.dart
  lib/screens/home/wallet_home_screen.dart
  lib/screens/settings/fake_balance_bottom_sheet.dart
  lib/screens/settings/settings_screen.dart
  lib/widgets/card/wallet_item_card.dart
Labels: 💫 feat

#437 feat(fiat-price): wallet list 화면 Fiat Price 표시
  lib/providers/view_model/home/wallet_list_view_model.dart
  lib/screens/home/wallet_list_screen.dart
Labels: 💫 feat

#441 [440] UTXO 선택화면 스크롤 버그
  lib/app.dart
  lib/providers/view_model/send/refactor/send_view_model.dart
  lib/providers/view_model/send/send_utxo_selection_view_model.dart
  lib/screens/send/refactor/send_screen.dart
  lib/screens/send/refactor/utxo_selection_screen.dart
  lib/screens/send/send_utxo_selection_screen.dart
  lib/widgets/card/send_utxo_sticky_header.dart
Labels: 🐛 bug, ♻️ refactor
