Repository noncelab/coconut_wallet, pull requests merged in 2025-04, with the labels that each got.

#155 fix(history-list): rbf history 정렬 되지 않는 버그 수정
  lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart
  lib/screens/wallet_detail/transaction_detail_screen.dart
Labels: 🐛 bug

#146 [14-1088] TransactionRecord 프로퍼티 수정
  lib/enums/network_enums.dart
  lib/enums/utxo_enums.dart
  lib/model/utxo/utxo_state.dart
  lib/model/wallet/transaction_record.dart
  lib/providers/node_provider/transaction/rbf_handler.dart
  lib/providers/node_provider/transaction/transaction_fetcher.dart
  lib/providers/node_provider/transaction/transaction_processor.dart
  lib/providers/transaction_provider.dart
  lib/providers/view_model/send/broadcasting_view_model.dart
  lib/providers/view_model/send/send_utxo_selection_view_model.dart
  lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart
  lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart
  lib/providers/view_model/wallet_detail/utxo_detail_view_model.dart
  lib/providers/view_model/wallet_detail/utxo_list_view_model.dart
  lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart
  lib/repository/realm/converter/transaction.dart
  lib/repository/realm/migration/migrator_ver2_1_0.dart
  lib/repository/realm/model/coconut_wallet_model.dart
  lib/repository/realm/model/coconut_wallet_model.realm.dart
  lib/repository/realm/transaction_repository.dart
  lib/screens/wallet_detail/transaction_detail_screen.dart
  lib/screens/wallet_detail/transaction_fee_bumping_screen.dart
  lib/utils/transaction_util.dart
  lib/widgets/card/transaction_item_card.dart
  test/mock/transaction_mock.dart
  test/providers/node_provider/transaction_manager_test.dart
Labels: ♻️ refactor

#157 refactor(sharedPrefKeys): sharedPrefsRepository 내부의 key 제거
  lib/constants/shared_pref_keys.dart
  lib/providers/auth_provider.dart
  lib/providers/preference_provider.dart
  lib/providers/view_model/onboarding/start_view_model.dart
  lib/repository/shared_preference/shared_prefs_repository.dart
  lib/services/app_review_service.dart
  test/services/shared_prefs_service_test.dart
Labels: ♻️ refactor

#156 fix(utxo_item_card): utxo_item_card의 isChange 수정
  lib/utils/derivation_path_util.dart
  lib/widgets/card/utxo_item_card.dart
Labels: ♻️ refactor

#160 fix(custom-tooltip): coconutTooltip으로 변경, 지갑상세 화면의 appbar title에 패딩 적용
  assets/i18n/kr.i18n.yaml
  lib/localization/strings.g.dart
  lib/localization/strings_kr.g.dart
  lib/screens/wallet_detail/address_list_screen.dart
  lib/screens/wallet_detail/transaction_detail_screen.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
  lib/screens/wallet_detail/wallet_info_screen.dart
  lib/widgets/overlays/custom_tooltip.dart
  pubspec.yaml
Labels: 🎨 UI

#161 [158] 지갑 추가 시 Outgoing UTXO 없는 오류 수정
  lib/model/utxo/utxo_state.dart
  lib/providers/node_provider/isolate/isolate_manager.dart
  lib/providers/node_provider/subscription/script_event_handler.dart
  lib/providers/node_provider/transaction/cpfp_handler.dart
  lib/providers/node_provider/transaction/rbf_handler.dart
  lib/providers/node_provider/transaction/transaction_fetcher.dart
  lib/providers/node_provider/transaction/transaction_processor.dart
  lib/providers/node_provider/utxo_manager.dart
  lib/repository/realm/converter/utxo.dart
  lib/repository/realm/transaction_repository.dart
  lib/services/electrum_service.dart
  test/providers/node_provider/transaction_manager_test.dart
  test/providers/node_provider/transaction_manager_test.mocks.dart
  test/providers/node_provider/utxo_manager_test.dart
  test/providers/node_provider/utxo_manager_test.mocks.dart
Labels: 🐛 bug

#167 [164] 네트워크 동시성 오류 수정
  lib/constants/network_constants.dart
  lib/model/node/wallet_update_info.dart
  lib/providers/node_provider/balance_manager.dart
  lib/providers/node_provider/isolate/isolate_manager.dart
  lib/providers/node_provider/isolate/isolate_state_manager.dart
  lib/providers/node_provider/state_manager.dart
  lib/providers/node_provider/subscription/script_callback_manager.dart
  lib/providers/node_provider/subscription/script_event_handler.dart
  lib/providers/node_provider/subscription/script_handler_util.dart
  lib/providers/node_provider/subscription/script_subscriber.dart
  lib/providers/node_provider/subscription/transaction_processing_state.dart
  lib/providers/node_provider/subscription_manager.dart
  lib/providers/node_provider/transaction/rbf_handler.dart
  lib/providers/node_provider/transaction/transaction_fetcher.dart
  lib/providers/node_provider/transaction/transaction_manager.dart
  lib/providers/node_provider/transaction/transaction_processor.dart
  lib/providers/node_provider/utxo_manager.dart
  lib/providers/view_model/wallet_detail/utxo_list_view_model.dart
  lib/providers/wallet_provider.dart
  lib/repository/realm/subscription_repository.dart
  lib/repository/realm/transaction_repository.dart
  lib/screens/home/wallet_list_screen.dart
Labels: 🐛 bug

#168 [166] utxo가 사라질 때 렌더링 에러
  lib/model/utxo/utxo_state.dart
  lib/providers/node_provider/utxo_manager.dart
  lib/screens/wallet_detail/utxo_list_screen.dart
  lib/widgets/card/utxo_item_card.dart
  lib/widgets/header/utxo_list_header.dart
  lib/widgets/header/wallet_detail_header.dart
  test/model/utxo/sort_utxo_list_test.dart
Labels: 🐛 bug

#169 [162] NodeProviderState 변경 오류 수정
  lib/providers/node_provider/isolate/isolate_enum.dart
  lib/providers/node_provider/isolate/isolate_handler.dart
  lib/providers/node_provider/isolate/isolate_state_manager.dart
  lib/providers/node_provider/state_manager.dart
  lib/providers/node_provider/state_manager_interface.dart
  lib/providers/node_provider/subscription/script_callback_manager.dart
  lib/providers/node_provider/subscription/script_event_handler.dart
  lib/providers/node_provider/subscription/script_handler_util.dart
  lib/providers/node_provider/transaction/transaction_fetcher.dart
  test/providers/node_provider/transaction_manager_test.dart
Labels: 🐛 bug

#172 [171] Realm 마이그레이션 로직 추가
  .gitignore
  lib/constants/realm_constants.dart
  lib/repository/realm/migration/migration.dart
  lib/repository/realm/migration/migrator_ver2_1_0.dart
  lib/repository/realm/migration/migrator_ver2_2_0.dart
  lib/repository/realm/model/coconut_wallet_model.dart
  lib/repository/realm/realm_manager.dart
  test/mock/realm/realm_transaction_mock.dart
  test/mock/realm/realm_utxo_mock.dart
  test/mock/realm/realm_wallet_address_mock.dart
  test/mock/realm/realm_wallet_balance_mock.dart
  test/mock/realm/realm_wallet_base_mock.dart
  test/repository/realm/realm_migration_test.dart
  test/repository/realm/test_realm_manager.dart
Labels: 💫 feat

#181 [176] 직접 입력 UI 및 기능 구현
  assets/i18n/kr.i18n.yaml
  assets/svg/circle-help.svg
  assets/svg/circle-warning.svg
  lib/app.dart
  lib/providers/view_model/home/wallet_add_input_view_model.dart
  lib/screens/home/wallet_add_input_screen.dart
  lib/screens/home/wallet_list_screen.dart
  pubspec.yaml
Labels: 💫 feat, 🎨 UI

#190 [185] TransactionInputOutputCard 생성 및 적용
  assets/i18n/kr.i18n.yaml
  lib/enums/transaction_enums.dart
  lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart
  lib/screens/wallet_detail/transaction_detail_screen.dart
  lib/screens/wallet_detail/utxo_detail_screen.dart
  lib/screens/wallet_detail/wallet_detail_screen.dart
  lib/utils/transaction_util.dart
  lib/widgets/card/transaction_input_output_card.dart
Labels: ♻️ refactor

#193 [174] 수수료 조회 화면에서 로딩이 계속되며 뒤로가기가 안됨
  assets/i18n/kr.i18n.yaml
  lib/app.dart
  lib/app_guard.dart
  lib/constants/network_constants.dart
  lib/providers/node_provider/isolate/isolate_manager.dart
  lib/providers/node_provider/node_provider.dart
  lib/screens/send/send_fee_selection_screen.dart
  lib/screens/wallet_detail/transaction_fee_bumping_screen.dart
  lib/services/network/socket/socket_manager.dart
  lib/widgets/overlays/coconut_loading_overlay.dart
  pubspec.yaml
Labels: 🐛 bug, 🎨 UI

#205 [203] 복사하기 버튼 변경
  assets/i18n/kr.i18n.yaml
  assets/svg/book.svg
  assets/svg/copy.svg
  lib/screens/wallet_detail/transaction_detail_screen.dart
  lib/screens/wallet_detail/utxo_detail_screen.dart
  lib/widgets/button/copy_text_container.dart
  lib/widgets/qrcode_info.dart
  pubspec.yaml
Labels: 🎨 UI
